name: Release Please

on:
  push:
    branches: [master]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: schummar-job
          bump-minor-pre-major: 'true'
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: pnpm/action-setup@v4
        with:
          version: 10
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
